### ISSUE TITLE
[Whisper Asr] Cannot transcript audio

### ISSUE THREAD

**Issue by masch** [djmango/obsidian-transcription#53] opened 2024-03-23 21:05 UTC
Hi!

I installed your plugin, and I'm trying to transcribe a talk in mp3 format. I embedded the file in a note and I select Transcribe file in view option and after I select the file nothing happens. The audio can be listened on the obsidian note.
I'm using the Whisper Asr version and it's running the container. Furthermore, I checked that the service is running because the URL http://localhost:9000 is returning the OAS definition.
Also, I check you plugin in debug mode and the only error I get is this, what I don't know if its from you plying or an Obsidian internal error.

```
Warning: vkCreateInstance: Found no drivers!
Warning: vkCreateInstance failed with VK_ERROR_INCOMPATIBLE_DRIVER
    at CheckVkSuccessImpl (../../third_party/dawn/src/dawn/native/vulkan/VulkanError.cpp:101)
    at CreateVkInstance (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:493)
    at Initialize (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:379)
    at Create (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:301)
    at operator() (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:556)
```

I don't know if it's good information to debug the issue, but I'm running Fedora Linux OS and use the Obsidian 1.5.11 flakpak version.

Thanks!

**Comment by ashepp** [comment] 2024-03-25 19:07
I'm seeing a similar issue. I'm running on a CPU only mode on an UnRaid Docker. I've supplied the URL in Obsidian options. I select the audio file and click on 'Add File Link' nothing happens. Have added debug toggle from options FWIW. Also I wasn't able to see it show up in the top right obsidian UI. I had to trigger the file upload from a hotkey.

**Comment by JeminiRiver** [comment] 2024-03-28 17:54
@ashepp I had the same problem in UnRaid when running, presumably, the default  **ASR_ENGINE** `openai_whisper`. I had to add the variable to my UnRaid docker instance and set it to `faster_whisper`. It got CPU-only mode working for me.

**Comment by ashepp** [comment] 2024-03-28 18:26
Thanks @JeminiRiver I had the ASR_ENGINE variable already there by default with a value of 'base'. Was there a different variable you had to create? When I tried to set it to faster_whisper it won't load the WebUI and I see the following error which seems to indicate it's not a valid value. 

    model = whisper.load_model(model_name, download_root=model_path)
  File "/app/.venv/lib/python3.10/site-packages/whisper/__init__.py", line 139, in load_model
    raise RuntimeError(
RuntimeError: Model faster_whisper not found; available models = ['tiny.en', 'tiny', 'base.en', 'base', 'small.en', 'small', 'medium.en', 'medium', 'large-v1', 'large-v2', 'large-v3', 'large']
[2024-03-28 11:07:26 -0700] [7] [INFO] Worker exiting (pid: 7)
[2024-03-28 11:07:26 -0700] [1] [ERROR] Worker (pid:7) exited with code 3
[2024-03-28 11:07:26 -0700] [1] [ERROR] Shutting down: Master
[2024-03-28 11:07:26 -0700] [1] [ERROR] Reason: Worker failed to boot.
[2024-03-28 11:11:03 -0700] [1] [INFO] Starting gunicorn 21.2.0
[2024-03-28 11:11:03 -0700] [1] [INFO] Listening at: http://0.0.0.0:9000 (1)
[2024-03-28 11:11:03 -0700] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-03-28 11:11:03 -0700] [7] [INFO] Booting worker with pid: 7
[2024-03-28 11:11:04 -0700] [7] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/app/.venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/app/.venv/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/app/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/app/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/app/.venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/app/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/app/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/app/.venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/app/webservice.py", line 19, in <module>
    from .openai_whisper.core import transcribe, language_detection
  File "/app/app/openai_whisper/core.py", line 16, in <module>

**Comment by ashepp** [comment] 2024-03-28 18:36
I think I figured it out. I need to add ASR_ENGINE as a variable with a value of 'faster_whisper'. Unfortunately I'm still not seeing anything happen in Obsidian when I click on 'add file link' for an MP4 audio / video recording I wanted to transcribe. Any ideas?

**Comment by JeminiRiver** [comment] 2024-03-28 18:38
> I think I figured it out. I need to add ASR_ENGINE as a variable with a value of 'faster_whisper'. Unfortunately I'm still not seeing anything happen in Obsidian when I click on 'add file link' for an MP4 audio / video recording I wanted to transcribe. Any ideas?
> 
> 

Check docker logs *shrugs*

**Comment by ashepp** [comment] 2024-03-28 18:47
This is all i'm seeing after trying to run. Looks like no IP is being set. Did you say you have this working with the plugin? 


[2024-03-28 11:32:28 -0700] [1] [INFO] Starting gunicorn 21.2.0
[2024-03-28 11:32:28 -0700] [1] [INFO] Listening at: http://0.0.0.0:9000 (1)
[2024-03-28 11:32:28 -0700] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-03-28 11:32:28 -0700] [7] [INFO] Booting worker with pid: 7
Downloading config.json: 100%|██████████| 2.31k/2.31k [00:00<00:00, 1.67MB/s]
Downloading vocabulary.txt: 100%|██████████| 460k/460k [00:00<00:00, 3.06MB/s]
Downloading tokenizer.json: 100%|██████████| 2.20M/2.20M [00:00<00:00, 6.05MB/s]
Downloading model.bin: 100%|██████████| 145M/145M [00:12<00:00, 11.3MB/s] 
[2024-03-28 11:32:51 -0700] [7] [INFO] Started server process [7]0:00, 6.08MB/s]
[2024-03-28 11:32:51 -0700] [7] [INFO] Waiting for application startup.
[2024-03-28 11:32:51 -0700] [7] [INFO] Application startup complete.
[2024-03-28 11:45:27 -0700] [1] [INFO] Handling signal: term
[2024-03-28 11:45:27 -0700] [7] [INFO] Shutting down
[2024-03-28 11:45:27 -0700] [7] [INFO] Error while closing socket [Errno 9] Bad file descriptor
[2024-03-28 11:45:27 -0700] [7] [INFO] Waiting for application shutdown.
[2024-03-28 11:45:27 -0700] [7] [INFO] Application shutdown complete.
[2024-03-28 11:45:27 -0700] [7] [INFO] Finished server process [7]
[2024-03-28 11:45:27 -0700] [7] [INFO] Worker exiting (pid: 7)
[2024-03-28 11:45:28 -0700] [1] [INFO] Shutting down: Master
[2024-03-28 11:45:47 -0700] [1] [INFO] Starting gunicorn 21.2.0
[2024-03-28 11:45:47 -0700] [1] [INFO] Listening at: http://0.0.0.0:9000 (1)
[2024-03-28 11:45:47 -0700] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-03-28 11:45:47 -0700] [7] [INFO] Booting worker with pid: 7
[2024-03-28 11:45:50 -0700] [7] [INFO] Started server process [7]
[2024-03-28 11:45:50 -0700] [7] [INFO] Waiting for application startup.
[2024-03-28 11:45:50 -0700] [7] [INFO] Application startup complete.

**Comment by djmango** [comment] 2024-04-04 16:47
Duplicate of #52, moving conversation there

**Closed by djmango** 2024-04-04 16:47 UTC
Labels: bug
